# Cómo trabajar con matrices

In [1]:
import tensorflow as tf
session = tf.Session()

/Users/raultoscanomiranda/opt/anaconda3/envs/mi_virtual_env_36_tensor_110/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/raultoscanomiranda/opt/anaconda3/envs/mi_virtual_env_36_tensor_110/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/raultoscanomiranda/opt/anaconda3/envs/mi_virtual_env_36_tensor_110/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, 

### 1. Cómo crear matrices

In [2]:
identity = tf.diag([1.,1.,1.,1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
A = tf.truncated_normal([3,4])
print(session.run(A))

[[ 0.4179375  -0.6674685   0.06698032 -0.5650093 ]
 [ 0.64243203 -1.1251109  -0.8959013   0.48531735]
 [ 0.5159693  -0.3489067   1.2623191   0.08223511]]


In [4]:
B = tf.fill([3,4], 1988.)
print(session.run(B))

[[1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]
 [1988. 1988. 1988. 1988.]]


In [5]:
C = tf.random_uniform([4,3])
print(session.run(C))

[[0.2326783  0.30509377 0.9850731 ]
 [0.62594223 0.07745874 0.29002976]
 [0.07694817 0.89747894 0.87957895]
 [0.5323919  0.9581988  0.25987208]]


In [6]:
import numpy as np
data = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices

In [7]:
print(session.run(A+B))

[[1986.4484 1987.044  1988.215  1989.8813]
 [1987.5258 1987.7804 1987.5609 1986.0992]
 [1988.2756 1986.5261 1987.4127 1988.4995]]


In [8]:
print(session.run(B-B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print(session.run(tf.matmul(A,C)))

[[0.45386314 0.7589061  0.9484688 ]
 [0.3541789  0.12342336 0.61435676]
 [0.21121094 0.420239   0.5154568 ]]


In [10]:
print(session.run(tf.matmul(A, identity)))

[[-0.81645995  0.3366893  -0.06508224 -1.1995679 ]
 [ 0.02458346 -0.7788593  -0.20735435  0.6998337 ]
 [-0.5868325  -0.7402592   0.259246    0.8211842 ]]


## 3. Tranpuesta, determinante, inversa

In [11]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [12]:
print(session.run(tf.transpose(A)))

[[ 0.44665474 -0.28575537 -0.11534715]
 [-0.20426933 -0.10617515  1.1948892 ]
 [-0.364871    1.874711   -0.2590806 ]
 [-0.56299394  0.39764896  0.89505166]]


In [13]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [14]:
E = tf.convert_to_tensor(np.array([[1.,2.,3.], [-3., -6., -1], [0., 5, -3]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [15]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


## 4. Descomposición

In [16]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios

In [17]:
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [18]:
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
